name: brew

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  brew:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master

      - name: Bump formulae
        uses: Homebrew/actions/bump-packages@master
        with:
          token: ${{ secrets.MY_HOMEBREW_RELEASE_GITHUB_TOKEN }}
          formulae: walk
